### ISSUE TITLE
mysql 8.0 Random password is not valid?

### ISSUE THREAD

**Issue by zengxc-1996** [Websoft9/ansible-mysql#3]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [x] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [x] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error


# service status 
normal


# error logs
journalctl -u init-apps
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: [46B blob data]
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: error: 'Can't connect to MySQL server on '::1:3306' (111)'
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: Check that mysqld is running on ::1 and that the port is 3306.
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: You can check this by doing 'telnet ::1 3306'
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: [52B blob data]
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: error: 'Can't connect to MySQL server on '127.0.0.1:3306' (111)'
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: Check that mysqld is running on 127.0.0.1 and that the port is 3306.
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: You can check this by doing 'telnet 127.0.0.1 3306'
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: [52B blob data]
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Apr 29 07:02:47 ip-172-31-42-186 bash[850]: Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!

```

### Bug Screenshot

![image](https://user-images.githubusercontent.com/63622990/116514309-6df69180-a8fd-11eb-94c3-dfd98b3b1931.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

Mysqld was not started before decryption.
![image](https://user-images.githubusercontent.com/63622990/116514836-24f30d00-a8fe-11eb-8f25-4626fc396501.png)
![image](https://user-images.githubusercontent.com/63622990/116514949-43f19f00-a8fe-11eb-84b8-b94ac73657b1.png)

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
Done
