### ISSUE TITLE
Install mysql 5.7 on aliyun ubuntu20 and mysql 5.6 on azure ubuntu 20 error 

### ISSUE THREAD

**Issue by zengxc-1996** [Websoft9/ansible-mysql#5]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [x] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [x] Azure
- [ ] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by zengxc-1996** [comment]
TASK [role_mysql : Change MySQL Directory] **********************************************************************************************************************************
fatal: [8.210.184.149]: FAILED! => {"changed": true, "cmd": "systemctl stop mysql\nrm -rf /data/mysql\nln -sf /var/lib/mysql /data/\nsystemctl start mysql\n", "delta": "0:00:00.023979", "end": "2021-05-27 17:22:06.098310", "msg": "non-zero return code", "rc": 1, "start": "2021-05-27 17:22:06.074331", "stderr": "Job for mysql.service failed because the control process exited with error code.\nSee \"systemctl status mysql.service\" and \"journalctl -xe\" for details.", "stderr_lines": ["Job for mysql.service failed because the control process exited with error code.", "See \"systemctl status mysql.service\" and \"journalctl -xe\" for details."], "stdout": "", "stdout_lines": []}

mysql can't start:

![image](https://user-images.githubusercontent.com/63622990/119803388-fe7ebc80-bf11-11eb-8b43-41644c9126f5.png)

**Comment by zengxc-1996** [comment]
tested on azure ubuntu 

```
root@mysql5:/home/websoft9# mysql
mysql: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```

No library files

**Comment by zengxc-1996** [comment]
Try to create a MySQL user;
Edit /etc/passwd,
add  this line

```
mysql:x:111:123:MySQL Server,,,:/var/lib/mysql:/bin/false
```

**Comment by zengxc-1996** [comment]
manual Install  on azure ubuntu 20.04:

This error occurred:

```
update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode
dpkg: dependency problems prevent configuration of mysql-community-client:
 mysql-community-client depends on libncurses5 (>= 6); however:
  Package libncurses5 is not installed.
 mysql-community-client depends on libtinfo5 (>= 6); however:
  Package libtinfo5 is not installed.

dpkg: error processing package mysql-community-client (--install):
 dependency problems - leaving unconfigured
Setting up mysql-community-source (5.6.51-1debian9) ...
dpkg: dependency problems prevent configuration of mysql-community-test:
 mysql-community-test depends on mysql-community-client (= 5.6.51-1debian9); however:
  Package mysql-community-client is not configured yet.

dpkg: error processing package mysql-community-test (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of mysql-testsuite:
 mysql-testsuite depends on mysql-community-test (= 5.6.51-1debian9); however:
  Package mysql-community-test is not configured yet.

dpkg: error processing package mysql-testsuite (--install):
 dependency problems - leaving unconfigured
Setting up libmysqlclient18:amd64 (5.6.51-1debian9) ...
dpkg: dependency problems prevent configuration of mysql-client:
 mysql-client depends on mysql-community-client (= 5.6.51-1debian9); however:
  Package mysql-community-client is not configured yet.

dpkg: error processing package mysql-client (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of mysql-community-server:
 mysql-community-server depends on mysql-client (= 5.6.51-1debian9); however:
  Package mysql-client is not configured yet.

dpkg: error processing package mysql-community-server (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-community-server (= 5.6.51-1debian9); however:
  Package mysql-community-server is not configured yet.

dpkg: error processing package mysql-server (--install):
 dependency problems - leaving unconfigured
Setting up libmysqlclient-dev (5.6.51-1debian9) ...
Setting up libmysqld-dev (5.6.51-1debian9) ...
dpkg: dependency problems prevent configuration of mysql-community-bench:
 mysql-community-bench depends on mysql-community-server (= 5.6.51-1debian9); however:
  Package mysql-community-server is not configured yet.

dpkg: error processing package mysql-community-bench (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Processing triggers for systemd (245.4-4ubuntu3.6) ...
Errors were encountered while processing:
 mysql-community-client
 mysql-community-test
 mysql-testsuite
 mysql-client
 mysql-community-server
 mysql-server
 mysql-community-bench

```

**Comment by jiaosir-cn** [comment]
Azure  UbuntuLTS20.04 mysql 5.6  test ok
```
Docker version 20.10.7, build f0df350
mysql  Ver 14.14 Distrib 5.6.51, for linux-glibc2.12 (x86_64) using  EditLine wrapper
Docker version 20.10.7, build f0df350
phpmyadmin version: "version": "5.1.1",
System version: Ubuntu 20.04
Image name: mysqljiaosir-UbuntuLTS20.04
```

**Comment by jiaosir-cn** [comment]
aliyun Ubuntu20.04  mysql5.7  test ok
```
Docker version 20.10.7, build f0df350
mysql  Ver 14.14 Distrib 5.7.33, for linux-glibc2.12 (x86_64) using  EditLine wrapper
Docker version 20.10.7, build f0df350
phpmyadmin version: "version": "5.1.1",
System version: Ubuntu 20.04
Image name: mysqljiaosir-Ubuntu20.04
```
